### ISSUE TITLE
lateral model - support additional species

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#291]
omg this repo is BOSS

Current hack changes `model/habitat_lateral/Makefile` call to watershed groups list to exclude LEUT

```
WSG = $(shell $(PSQL) -AtX -c "SELECT watershed_group_code FROM bcfishpass.param_watersheds where watershed_group_code NOT IN ('ELKR', 'LEUT')")
``` 
Working again.  error was:
```
make[1]: Entering directory '/Users/airvine/Projects/repo/bcfishpass/model/habitat_lateral'
mkdir -p data/temp/LEUT
python valley_confinement.py LEUT -o data/temp/LEUT/valleys.tif -d data/temp/LEUT
2023-02-16 09:41:34,482 __main__     INFO     LEUT - Processing extent 960134.118,919154.936,1052995.159,965742.825
2023-02-16 09:41:34,623 __main__     INFO     LEUT - rasterizing streams
Traceback (most recent call last):
  File "/Users/airvine/Projects/repo/bcfishpass/model/habitat_lateral/valley_confinement.py", line 728, in <module>
    cli()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/newgraph/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/newgraph/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/newgraph/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/newgraph/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/airvine/Projects/repo/bcfishpass/model/habitat_lateral/valley_confinement.py", line 724, in cli
    valley_confinement(watershed_group_code, db_url, out_file, workdir, dem_path=dem, **config)
  File "/Users/airvine/Projects/repo/bcfishpass/model/habitat_lateral/valley_confinement.py", line 351, in valley_confinement
    get_streams(db, bounds, minimum_drainage_area, DEM, dem_meta, data_path)
  File "/Users/airvine/Projects/repo/bcfishpass/model/habitat_lateral/valley_confinement.py", line 208, in get_streams
    A = features.rasterize(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/newgraph/lib/python3.9/site-packages/rasterio/env.py", line 394, in wrapper
    return f(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/newgraph/lib/python3.9/site-packages/rasterio/features.py", line 327, in rasterize
    raise ValueError('No valid geometry objects found for rasterize')
ValueError: No valid geometry objects found for rasterize
make[1]: *** [Makefile:108: data/temp/LEUT/valleys.tif] Error 1
make[1]: Leaving directory '/Users/airvine/Projects/repo/bcfishpass/model/habitat_lateral'
make: *** [Makefile:222: model/habitat_lateral/.make/habitat_lateral] Error 2
```

**Comment by smnorris** [comment]
lateral habitat is purely salmon/steelhead at the moment, so LEUT is not going to work. 

The valley confinement script should work if LEUT was added to the list of watersheds included in `param_watersheds` but the habitat lateral processing in `habitat_lateral.py` would need updating to work more generally.

**Comment by smnorris** [comment]
I'm thinking the easiest way to do this is make the assumption that the user has only generated access/habitat outputs for the species they are interested in. Build unconfined valleys for all streams defined as accessible to any species, and build lateral habitat for all streams noted as having habitat for any species.

**Comment by NewGraphEnvironment** [comment]
Aha. Thanks!

you are probably already on it but I needed to make a few very minor changes to make the `model/habitat_lateral/sql/habitat_lateral.sql` script run (val as value in first table and add schema to call to drop `habitat_lateral_disconnected_rail` at the end of the script. 

A few target paths needed to be updated as well in main `Makefile`


Changes are here. https://github.com/NewGraphEnvironment/bcfishpass/tree/ng

**Comment by smnorris** [comment]
yeah, I think I have captured a few of those already. Haven't taken time to figure out how to get the merge of the output tifs to work yet though.

**Comment by smnorris** [comment]
fixed with https://github.com/smnorris/bcfishpass/commit/0ab8a3900d9ac24616845464b10ff15b49c1bff4, but not yet merged. A config option for what species / roads / rails to include would be valuable
