### ISSUE TITLE
GHA docs build failing

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#299]
```[sphinx-action] Running: ['make', 'html', '-e']
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 152, in build_all_docs
    return_code, annotations = build_docs(github_env.build_command, docs_dir)
  File "/sphinx_action/action.py", line 134, in build_docs
    with open(log_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sphinx-log'
```

Nothing changed on this end, issue must be with at ammaraskar/sphinx-action@master, sphinx, or perhaps GHA itself. 
Same error occurs when building `fwapg` docs.

**Comment by smnorris** [comment]
found and copied PR updating previous action: https://github.com/adempiere/docs/blob/master/.github/workflows/main.yml
